[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Michael Baudler <hello@mrbandler.dev>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/mrbandler/flow"
homepage = "https://github.com/mrbandler/flow"
documentation = "https://docs.rs/flow"
readme = "README.md"
keywords = ["notes", "outliner", "knowledge-base", "cli", "productivity"]
categories = ["command-line-utilities", "text-editors"]
rust-version = "1.91.1"

[workspace.dependencies]
flow-core = { path = "crates/flow-core" }
flow-cli = { path = "crates/flow-cli" }
flow-common = { path = "crates/flow-common" }
flow-errors = { path = "crates/flow-errors" }
flow-app = { path = "crates/flow-app" }
flow-tui = { path = "crates/flow-tui" }
flow-gui = { path = "crates/flow-gui" }
flow-server = { path = "crates/flow-server" }

tokio = { version = "1.52", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
miette = { version = "7.6", features = ["fancy"] }
thiserror = "2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
