[package]
name = "flow-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
flow-errors = { workspace = true }
tokio = { workspace = true }
miette = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
loro = "1.12.0"
cross-xdg = "2.1"

[lints]
workspace = true
