blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://flow.mrbandler.dev/
    about: Check the README for usage information
  - name: 💬 Discussions
    url: https://github.com/mrbandler/flow/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
