blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/mrbandler/flow/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
  - name: 📚 Documentation
    url: https://github.com/mrbandler/flow#readme
    about: Check the README for usage information
